knp_paginator:
    page_range: 5                       # nombre de liens de page affichés
    default_options:
        page_name: page                # nom du paramètre de page
        sort_field_name: sort          # nom du paramètre de tri
        sort_direction_name: direction # nom du paramètre de direction
        distinct: true                 # garantit des résultats distincts
    template:
        pagination: '@KnpPaginator/Pagination/tailwind_pagination.html.twig'     # template de pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # template pour les liens triables