security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
            # IMPORTANT: pas de remember_me ici pour vraiment forcer la reconnexion
            access_denied_handler: App\Security\AccessDeniedHandler

    # Hiérarchie inchangée
    role_hierarchy:
        ROLE_ADMIN: ['ROLE_CONSULTATION', 'ROLE_CARISTE', 'ROLE_USER']
        ROLE_CARISTE: ['ROLE_USER']
        ROLE_CONSULTATION: ['ROLE_USER']

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/account/sessions, roles: ROLE_USER }   # page de gestion des sessions
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/consultation, roles: ROLE_CONSULTATION }
        - { path: ^/cariste, roles: ROLE_CARISTE }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
