# config/services.yaml

parameters:
    # Durée de vie absolue des sessions (12h = 43200 secondes)
    app.sessions.ttl_seconds: 43200
    # Nombre maximum de sessions actives par utilisateur (1 = session unique)
    app.sessions.max_active: 1

services:
    # configuration par défaut
    _defaults:
        autowire: true
        autoconfigure: true

    # rend tout src/ disponible comme service
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # inclure explicitement les entités comme services si besoin
    App\Entity\:
        resource: '../src/Entity'
        public: true

    # définition explicite d’un service existant
    App\Service\InventaireImportService:
        autowire: true
